---
layout: cv
title: Chase Smith
---
Tenaious Innovative Charitable 

<div id="webaddress">
<a href="chased.smith1@gmail.com">chased.smith1@gmail.com</a>
</div>


## Currently

Making custom in house applications to streamline os updating automation with optimized patching windows.

### Specialized in

Cybersecurity, AI, Excel Sheets, Docker, Neo4j, Streamlit, API.

### Research interests

Making a AI side project to generate an effecitve win stragey for a fun card game called "Minecraft Explorers".

## Education

`2019 - Present`

__Brigham Young University Idaho__

- CIT Major

## Volunteer Work

`2021 -2023`

__The Church of Jesus Christ of Latter-day Saints__

Missionary

- As a missionary, I voluntarily ministered and diligently preached The Gospel of Jesus Christ for 2 years.

- I was entrusted with leadership roles such as “Zone Leader,” “District Leader,” and “Trainer.” I helped to
gather and report metrics to senior leadership. Most importantly, I was able to offer guidance and
encouragement to the 12 missionaries under my care.

- Became proficient in speaking the Spanish language.

## Certificates

- `Comptia Security +`
- `MS-900`
- `SC-900`
- `AI-900`

## Occupation

`Jun 2019 - May 2020 (with a one-semester sabbatical for school)`

__Lyn-Tron, Inc.__ 
2nd Operations Technician

- As a 2nd Ops technician, I inspected manufactured parts and made any necessary corrections prior to shipment.
- I suggeseted and helped maintain robotics to accelerate production capabilities.
- I operated complex machinery to re-work metal and plastic parts to prepare them for shipment.

`2023-Present`

__Philantech3__ 
Security Maintence

- I manage the security for over 1,400 endpoints including 3rd party and os patching.
- I help track and format data about our current security posture and provide actionable suggestions for improvement.
- I have deployed in house applications that help machines get updated.
- I've also implmented an array of different automations to help boost efficiency.

<!-- ### Footer

Last updated: Oct 2024 -->